"""empty message

Revision ID: 2b2d90fc6cdd
Revises: 
Create Date: 2021-11-17 17:02:54.944545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2d90fc6cdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('isbn', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('public_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('cover_photo', sa.String(length=100), nullable=True),
    sa.Column('trade_price', sa.Integer(), nullable=True),
    sa.Column('retail_price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('isbn'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
